### ISSUE TITLE
toradora coalgirls

### ISSUE THREAD

**Issue by gfmate123** [gnoling/UnlinkMKV#10]
tried this app and it works but the new video fps is different from original video why?
it went from 23.976 to 23.641

**Comment by stefanSchuhbaeck** [comment]
Hi,
I needed to change `Segment UID` to `Segment-UID` in Line [732](https://github.com/gnoling/UnlinkMKV/blob/c38e9b87c2dbe6aac5c401cf66a42c153690dbc7/unlinkmkv#L732) and [733](https://github.com/gnoling/UnlinkMKV/blob/c38e9b87c2dbe6aac5c401cf66a42c153690dbc7/unlinkmkv#L733) to get the script working with my mkv-Files. Don't no if there is a standard for this but though you shoud know.

**Comment by gnoling** [comment]
This would depend on the options used. If fix video or fix audio is used, the streams are re-encoded via ffmpeg. If not it would entirely depend on the source streams, how mkvtoolnix deals with differences, and differences in the sources.
