### ISSUE TITLE
Getting Segment ID

### ISSUE THREAD

**Issue by stefanSchuhbaeck** [gnoling/UnlinkMKV#11]
Hi,
I needed to change `Segment UID` to `Segment-UID` in Line [732](https://github.com/gnoling/UnlinkMKV/blob/c38e9b87c2dbe6aac5c401cf66a42c153690dbc7/unlinkmkv#L732) and [733](https://github.com/gnoling/UnlinkMKV/blob/c38e9b87c2dbe6aac5c401cf66a42c153690dbc7/unlinkmkv#L733) to get the script working with my mkv-Files. Don't no if there is a standard for this but though you shoud know.

**Comment by gnoling** [comment]
What version of mkvtoolnix are you using? I wonder if the output has changed.

**Comment by stefanSchuhbaeck** [comment]
Hi,

sorry for the delay. I did the stuff on the computer of a friend of mine and I only get hands on it now to check the Version. I’m also not really into how the mkvtoolnix works, I only now a little bit of pearl. I hope this helps you.

Mkvinfo v7.9.0 (Birds) 64Bit OS X 10.11.4

---

Stefan Schuhbäck
Mobil: +49 (0) 0174 6178456
Email: info@schuhbaeck.eu

Von: Garret Noling [mailto:notifications@github.com]
Gesendet: Donnerstag, 7. April 2016 21:16
An: gnoling/UnlinkMKV UnlinkMKV@noreply.github.com
Cc: Stefan Schuhbäck stefan@schuhbaeck.eu
Betreff: Re: [gnoling/UnlinkMKV] Getting Segment ID (#11)

What version of mkvtoolnix are you using? I wonder if the output has changed.
