### ISSUE TITLE
flag name change?

### ISSUE THREAD

**Issue by Jolar** [gnoling/UnlinkMKV#12]
Just noticed it still says --fix-video and not -fv/--fixvideo in the documentation README.pod. Took some time before I vaguely remembered something about this...

Are there other changes in the flag names? I get
...
       generating chapter file
         loading chapters
         non-default chapter dropped
...
all the time with some encodes, and --ignore-default-flag doesn't do anything. Not that I know what it's supposed to do and if it's applicable in this situation, but I thought I should check if this name has changed as well anyway. edit:just after posting I tried --ignoredefaultflag and that did the trick... :)

Also, I couldn't for the love of my life figure out how to make "default" chapters that unlinkmkv would recognize. MKVToolNixGUI doesn't allow any flags or options to be set for chapter tracks, not version 9.1.0 at least. You just mux chapters or not. I couldn't produce any ordered chapters files with this version that unlinkmkv could be used on without the --ignoredefaultflag option. Any thoughts on this?

**Comment by gnoling** [comment]
You're absolutely correct, the documentation was lagging. Updated.

Default chapters actually refers to default editions in the chapters. By default if the edition flag exists UnlinkMKV automatically selects the default/enabled edition. The option exists to ignore the flag as a result of a release I encountered at one point where the flag existed -- but the only edition present was disabled. That option, the playres\* options, and really the --(no)-chapters options all really exist to work around various issues but typically shouldn't be required.
