### ISSUE TITLE
Drop the default ordered flag

### ISSUE THREAD

**Issue by hilts-vaughan** [gnoling/UnlinkMKV#14]
https://github.com/hilts-vaughan/UnlinkMKV-GUI/commit/0030643d281794427a20ba625911bb918aca1ecd

Someone had submitted this commit to me -- I landed it but am trying to stray away from customizations now since you support Win32.

I can submit PRs if needed

**Comment by gnoling** [comment]
Apparently I never closed this, fixed ~7 months ago
