### ISSUE TITLE
Trojan Detection!

### ISSUE THREAD

**Issue by JLChamberlain** [gnoling/UnlinkMKV#16]
When I went to install this software Norton 360 blocked multiple Trojan files, why is there Trojans in the software?

**Comment by gnoling** [comment]
Can you elaborate please, maybe include the scan report? Also, did you download this from github here or somewhere else?

dist/unlinkmkv-win32.7z contains a packed executable (unlinkmkv.exe, which is a perl packaged program which is packed by nature) and dists of ffmpeg and mkvtoolnix, which are stock.

**Comment by gnoling** [comment]
I ran everything inside that archive against clamav, and the executables individually against jotti's online scanner (which scans using a bunch of different AV) and am not seeing anything. Unlinkmkv.exe itself shows as being packed in clamav, which it should, because it is due to how that's built and clamav not being great at that -- which just means its compressed internally.

**Comment by JLChamberlain** [comment]
I downloaded it from your GitHub Account and this is what Norton 360 told me:
![screenshot 33](https://cloud.githubusercontent.com/assets/22307144/19446257/e7f5b790-948f-11e6-9c42-6d1d0bdefef7.png)

**Comment by gnoling** [comment]
Okay. I went ahead and filed a false positive report with them, we'll see how it goes. Googling it it sounds like some other software has been reported like that too.

In the meantime you can always use the non-packed/compiled version, but that does mean you'd need to install perl and related perl modules to be able to run it.

**Comment by gnoling** [comment]
"In relation to submission 6276.

Upon further analysis and investigation we have verified your submission and as such this detection will be removed from our products.

The updated detection will be distributed in the next set of virus definitions, available via LiveUpdate or from our website at http://securityresponse.symantec.com/avcenter/defs.download.html

Please note that whitelisting can take up to 24 hours to take effect."

I got this from Symantec this morning.
