### ISSUE TITLE
Finished files disappearing

### ISSUE THREAD

**Issue by counterfit** [gnoling/UnlinkMKV#17]
While processing the entire directory, I get the expected output:
>(G_P) Patlabor TV 1080p/(G_P) Patlabor TV 47(x264 1080p)(86067C39).mkv contains segmented chapters
>      generating chapter file
>         loading chapters
>         non-default chapter dropped
>      writing chapter temporary file
>      looking for segment parts
>      checking that all required segments were found
>      extracting attachments
>      creating splits
>      setting parts
>      extracting subs
>      making substyles unique
>      mashing unique substyles to all parts
>      remuxing subtitles
>      building file
>      fixing subs, again... (maybe an mkvmerge issue?)
>      moving built file to final destination

Everything seems to work, except the files disappear after being moved. They don't seem to exist anywhere on the filesystem at all after that.

**Comment by gnoling** [comment]
Try it with:
**-ll TRACE**

To give extremely verbose output and paste them back.

**Comment by counterfit** [comment]
I'll have the results soon. Trying to figure this out has led to a rabbit hole of software updates and hardware issues, including a hard drive replacement.
Short version: I think the files might not actually be using linked segments, but they're being recognized as if they are.

**Comment by gnoling** [comment]
I went ahead and tracked down this release based on the filename from your initial report. It looks like the two options you'll need to use are:

--ignoredefaultflag --fixvideo

The default flag is causing your reported issue (just use that option to work around it), however after you get past that you'll find that the ending video wasn't encoded in a way (video stream only) that can be appended successfully, so you'll also have to use --fixvideo to re-encode the video streams.

**Comment by counterfit** [comment]
An initial try with your suggestion also didn't work, but then I updated mkvtoolnix and then it worked as expected. The clue was trying to redo a series that I knew for a fact used linked segments, and no linked segments being found.

**Comment by gnoling** [comment]
Was the mkvtoolnix version you used the one bundled in the dist dir? Maybe I need to update it.

**Comment by counterfit** [comment]
I think it was a older version I had installed through Homebrew.

**Comment by Elbadry1** [comment]
i'm downloading mini mkv anime from the site which encoded it 10 bit , so after using unlink merge the resulted file is corrupted , any soln

**Comment by gnoling** [comment]
Can you please open a new issue? I'm going to close this one.

As for 10 bit, that should make no difference as long as your ffmpeg is new enough to support it. The resultant file won't be 10-bit however.
