### ISSUE TITLE
No subtitles

### ISSUE THREAD

**Issue by djrick1994** [gnoling/UnlinkMKV#18]
I'm having some problems unlinking the Coalgirls bluray release of Owarimonogatari.
The program creates a mkv with the episode, opening and ending combined , but it's missing the subtitle track.
The resulting MKV file does contain the correct fonts according to MKVExtract.
I've tried a couple of different episodes (some using different openings and endings), but the result stays the same.
This is the console output that i'm getting:
http://pastebin.com/jC6zqN7v

**Comment by gnoling** [comment]
Can you run it with "-ll TRACE" and paste that output? It should contain far more detail

**Comment by djrick1994** [comment]
Here you go: http://pastebin.com/jBJv9DPW

**Comment by gnoling** [comment]
This looks like the same issue as #9, you should be able to work around it temporarily by setting locale to english.

**Comment by djrick1994** [comment]
Yep, that solved the problem.
Thank you :)
