### ISSUE TITLE
opening and ending problem with 10 bit encoding

### ISSUE THREAD

**Issue by Elbadry1** [gnoling/UnlinkMKV#19]

**Comment by Elbadry1** [comment]
the episode reassembled properly but video file of opening  and ending corrupted

**Comment by gnoling** [comment]
That does sound like it's either not re-encoding at all, or your version of ffmpeg can't decode 10-bit (newer ones definitely can, I do it all the time). Try it with a "-ll TRACE" and pasting the output.

**Comment by Elbadry1** [comment]
after your previous commenti have downloaded latsest version of ffmpeg ,so if you wanna try it you can download first episode , opening ,ending of this link "http://hi10anime.com/ajin/ajin/" , sorry but what you means by "-ll TRACE"

**Comment by gnoling** [comment]
Add it to your command line, like:

"unlinkmkv -ll TRACE ..."

**Comment by Elbadry1** [comment]
C:\Users\Mohamed Fattouh>unlinkmkv -ll TRACE
'unlinkmkv' is not recognized as an internal or external command,
operable program or batch file.

**Comment by gnoling** [comment]
How did you run this the first time? You should use the same command line but add -ll TRACE to it with your other arguments. It just turns up the logging level and includes a lot more detail.

**Comment by Elbadry1** [comment]
i am very sorry but i didn't run it from cmd i always run it from UnlinkMKV-GUI as adminstrator '
can you give me an example to run it from cmd

**Comment by gnoling** [comment]
That's a separate project, I'm not sure if the options are even the same as it bundles its own version of unlinkmkv.

**Comment by Elbadry1** [comment]
have you tested it

**Comment by gnoling** [comment]
I wouldn't mind doing so but no, that site appears to require registration and I'm not particularly interested in signing up.

**Comment by Elbadry1** [comment]
sorry but the problem in software or i haven't installed requirements properly

**Comment by Elbadry1** [comment]
here is the output
[New Text Document.txt](https://github.com/gnoling/UnlinkMKV/files/694324/New.Text.Document.txt)

**Comment by gnoling** [comment]
You might want to try submitting an issue to the UnlinkMKV-GUI project instead for problems with that software.

If you want to try the windows version of *this* software you either need to install (quite a bit) of requirements for the source version to work, or try the win32 compiled version in the dist/ sub directory of this repository. Be mindful that the console application in the dist/ directory is **not** the same script that UnlinkMKV-GUI appears to use.

That log doesn't appear to run the encoding that fix video does to resolve this sort of issue (being mindful that --fixvideo re-encodes the video streams and it will result in an 8-bit file), so please try the version in the dist directory.

If you extract that to say, c:\unkinkmkv, your command line would be something like:

> c:\unlinkmkv\unlinkmkv -ll TRACE --fixvideo "C:/Users/Mohamed Fattouh/Downloads/Compressed/f/"

Based on your log.

**Comment by gnoling** [comment]
Actually, that may be a slightly older version of unlinkmkv, and fix video might be --fix-video in that version (I renamed it in later versions).

**Comment by Elbadry1** [comment]
sorry for disturbance and thank you very much
