### ISSUE TITLE
UnlinkMKV fails to merge Coalgirl's Tsukimonogatari 01 properly

### ISSUE THREAD

**Issue by hilts-vaughan** [gnoling/UnlinkMKV#2]
Running UnlinkMKV against it with various flag's does not seem to work. It stutters a lot, especially within the first few seconds. It's file size also ends up being much smaller than the original files.

**Comment by hilts-vaughan** [comment]
It looks like there may have been an issue with there release -- let me investigate a bit more first.

**Comment by gnoling** [comment]
Can you link me the release in question, I believe they typically post it on their blog / a link to that is fine.

**Comment by hilts-vaughan** [comment]
http://coalgirls.wakku.to/9627/tsukimonogatari

With releases this large, it's possible I failed a hash check or something. I will also try getting a fresh copy.

**Comment by mustang651** [comment]
I also have problems with s02e11 of Nisekoi in 1080p: http://coalgirls.wakku.to/9830/nisekoi-second-season

**Comment by gnoling** [comment]
You should open a new issue when its a different release. Could you create a new issue for nisekoi?
