### ISSUE TITLE
Some mkv metadata missing/wrong

### ISSUE THREAD

**Issue by grenzor** [gnoling/UnlinkMKV#26]
Been using UnlinkMKV for a little while and it seems it misses out on some information for example the title and language metadata of subtitles (but I think it also happens with audio/video streams).

I also noticed the final unlinked file if it has a movie name metadata will named after the opening rather than the main video (e.g. Series - OP1 rather than Series - EP1).

Is it possible to fix this?

Thanks for the great program!

**Comment by gnoling** [comment]
Yeah, this is actually the same as issue #7, though it effects all metadata. Closing as a duplicate.
