### ISSUE TITLE
Output Failing to Build

### ISSUE THREAD

**Issue by ztrouy** [gnoling/UnlinkMKV#27]
I am having an issue getting UnlinkMKV to provide a working output file. Using either the most up-to-date versions Strawberry Perl, MKVToolNix, ffmpeg, and other dependencies, or the versions specified in the readme, or those that are supplied with UnlinkMKV, I experience one of two issues. 

When using default settings (more specifically everything but chapters and fixsubtitles being set to 0), the final result is "file failed to build". This appears to have something to do with the subtitles, as after unlinkmkv attempts to fix subs, it tries again "fixing subs, again... (maybe an mkvmerge issue?)". At the end of this, no output file is created.

When modifying the .ini to set fixsubtitles to 0, an output file is created, however, if you attempt to view it the video player says "Cannot render the file". Using a mix of fixaudio and fixvideo settings does not remedy the situation either. 

Here are the full logs-

> C:\Users\XXXX\Desktop\Test>unlinkmkv s01e01.mkv
UnlinkMKV
      Options
         chapters: 1
         ffmpeg: C:\MKVToolNix\unlinkmkv\ffmpeg\bin\ffmpeg.EXE
         fixaudio: 0
         fixsubtitles: 1
         fixvideo: 0
         ignoredefaultflag: 0
         mkvext: C:\MKVToolNix\unlinkmkv\mkvtoolnix\mkvextract.EXE
         mkvinfo: C:\MKVToolNix\unlinkmkv\mkvtoolnix\mkvinfo.EXE
         mkvmerge: C:\MKVToolNix\unlinkmkv\mkvtoolnix\mkvmerge.EXE
         outdir: C:\Users\XXXX\Desktop\Test\UMKV
         tmpdir: C:\Users\XXXX\Desktop\Test\UMKV.tmp
   processing C:\Users\XXXX\Desktop\Test\s01e01.mkv
      checking if file is segmented
         file contains segmented chapters
      generating chapter file
         loading chapters
         non-default chapter dropped
      writing chapter temporary file
      looking for segment parts
         checking that all required segments were found
         all segments found
      extracting attachments
      setting parts
      extracting subs
      making substyles unique
      mashing unique substyles to all parts
      remuxing subtitles
      building file
      fixing subs, again... (maybe an mkvmerge issue?)
      moving built file to final destination
         file failed to build

> C:\Users\XXXX\Desktop\Test>unlinkmkv s01e01.mkv
UnlinkMKV
      Options
         chapters: 1
         ffmpeg: C:\MKVToolNix\unlinkmkv\ffmpeg\bin\ffmpeg.EXE
         fixaudio: 0
         fixsubtitles: 0
         fixvideo: 0
         ignoredefaultflag: 0
         mkvext: C:\MKVToolNix\unlinkmkv\mkvtoolnix\mkvextract.EXE
         mkvinfo: C:\MKVToolNix\unlinkmkv\mkvtoolnix\mkvinfo.EXE
         mkvmerge: C:\MKVToolNix\unlinkmkv\mkvtoolnix\mkvmerge.EXE
         outdir: C:\Users\XXXX\Desktop\Test\UMKV
         tmpdir: C:\Users\XXXX\Desktop\Test\UMKV.tmp
   processing C:\Users\XXXX\Desktop\Test\s01e01.mkv
      checking if file is segmented
         file contains segmented chapters
      generating chapter file
         loading chapters
         non-default chapter dropped
      writing chapter temporary file
      looking for segment parts
         checking that all required segments were found
         all segments found
      extracting attachments
      setting parts
      building file
      fixing subs, again... (maybe an mkvmerge issue?)
      moving built file to final destination

> C:\Users\XXXX\Desktop\Test>unlinkmkv s01e01.mkv
UnlinkMKV
      Options
         chapters: 1
         ffmpeg: C:\MKVToolNix\unlinkmkv\ffmpeg\bin\ffmpeg.EXE
         fixaudio: 0
         fixsubtitles: 0
         fixvideo: 0
         ignoredefaultflag: 0
         mkvext: C:\MKVToolNix\mkvextract.EXE
         mkvinfo: C:\MKVToolNix\mkvinfo.EXE
         mkvmerge: C:\MKVToolNix\mkvmerge.EXE
         outdir: C:\Users\XXXX\Desktop\Test\UMKV
         tmpdir: C:\Users\XXXX\Desktop\Test\UMKV.tmp
   processing C:\Users\XXXX\Desktop\Test\s01e01.mkv
      checking if file is segmented
         file contains segmented chapters
      generating chapter file
         loading chapters
         non-default chapter dropped
      writing chapter temporary file
      looking for segment parts
         checking that all required segments were found
         all segments found
      extracting attachments
      setting parts
      building file
      fixing subs, again... (maybe an mkvmerge issue?)
      moving built file to final destination

(Edit) I also tried setting "ignoredefaultflag" to 1, which produced a file that is watchable, but has no sound, and the video has heavy artifacting as well. Here is the log-

> C:\Users\XXXX\Desktop\Test>unlinkmkv s01e01.mkv
UnlinkMKV
      Options
         chapters: 1
         ffmpeg: C:\MKVToolNix\unlinkmkv\ffmpeg\bin\ffmpeg.EXE
         fixaudio: 1
         fixsubtitles: 0
         fixvideo: 1
         ignoredefaultflag: 1
         mkvext: C:\MKVToolNix\unlinkmkv\mkvtoolnix\mkvextract.EXE
         mkvinfo: C:\MKVToolNix\unlinkmkv\mkvtoolnix\mkvinfo.EXE
         mkvmerge: C:\MKVToolNix\unlinkmkv\mkvtoolnix\mkvmerge.EXE
         outdir: C:\Users\XXXX\Desktop\Test\UMKV
         tmpdir: C:\Users\XXXX\Desktop\Test\UMKV.tmp
   processing C:\Users\XXXX\Desktop\Test\s01e01.mkv
      checking if file is segmented
         file contains segmented chapters
      generating chapter file
         loading chapters
         non-default chapter kept on purpose
         internal
            chapter start   00:00:0.000000001
            chapter end     00:01:21.998000001
            offset  start   00:00:00.000000000
            offset  end     00:01:21.998000001
            chapter enabled 1
         external
            chapter start   00:01:21.998000001
            chapter end     00:02:52.025000002
            offset  start   00:01:30.027000001
            offset  end     00:02:52.025000002
            chapter enabled 1
         internal
            chapter start   00:02:52.067000002
            chapter end     00:10:7.961000002
            offset  start   00:01:30.027000001
            offset  end     00:10:7.961000002
            chapter enabled 1
         internal
            chapter start   00:10:8.002000002
            chapter end     00:22:29.994000002
            offset  start   00:01:30.027000001
            offset  end     00:22:29.994000002
            chapter enabled 1
         external
            chapter start   00:22:29.994000002
            chapter end     00:24:0.021000003
            offset  start   00:03:0.054000002
            offset  end     00:24:0.021000003
            chapter enabled 1
         internal
            chapter start   00:24:0.062000003
            chapter end     00:24:30.009000003
            offset  start   00:03:0.054000002
            offset  end     00:24:30.009000003
            chapter enabled 1
      writing chapter temporary file
      looking for segment parts
         found part C:\Users\XXXX\Desktop\Test\UMKV.tmp\3864\parts\op.mkv
         found part C:\Users\XXXX\Desktop\Test\UMKV.tmp\3864\parts\ed.mkv
         checking that all required segments were found
         all segments found
      extracting attachments
         found Bahij_TheSansArabic-Black.ttf
         found formata-regular.otf
         found HANDYHANDY.ttf
         found HelveticaCdBlk.ttf
         found Impress BT.ttf
         found Kharabeesh Font.ttf
         extracting attachments...
         found FromWhereYouAre.ttf
         found Typomoderno bold.ttf
         extracting attachments...
         found FOT-ChiaroStd-B.otf
         found libbysr.ttf
         extracting attachments...
         creating 3 splits from C:\Users\XXXX\Desktop\Test\s01e01.mkv
      setting parts
      encoding parts
         C:\Users\XXXX\Desktop\Test\UMKV.tmp\3864\parts\split-001.mkv
         C:\Users\XXXX\Desktop\Test\UMKV.tmp\3864\parts\op.mkv
         C:\Users\XXXX\Desktop\Test\UMKV.tmp\3864\parts\split-002.mkv
         C:\Users\XXXX\Desktop\Test\UMKV.tmp\3864\parts\ed.mkv
         C:\Users\XXXX\Desktop\Test\UMKV.tmp\3864\parts\split-003.mkv
      building file
      fixing subs, again... (maybe an mkvmerge issue?)
      moving built file to final destination
         file failed to build

Any help getting this working would be much appreciated!

**Comment by gnoling** [comment]
Please try it again with the "-ll trace" option so we can see what's going on

**Comment by ztrouy** [comment]
Did just that, to give you as much info as I could! I'll have to attach the .txt files, as they're really long and the styling on this website really messes with them. 

If you need anything else, just say and I'll happily provide!
[IgDefFlag1.txt](https://github.com/gnoling/UnlinkMKV/files/1573283/IgDefFlag1.txt)
[Sub0.txt](https://github.com/gnoling/UnlinkMKV/files/1573284/Sub0.txt)
[Default.txt](https://github.com/gnoling/UnlinkMKV/files/1573285/Default.txt)
[Aud1Vid1Sub0.txt](https://github.com/gnoling/UnlinkMKV/files/1573286/Aud1Vid1Sub0.txt)

**Comment by gnoling** [comment]
I suspect it's a problem with the subtitles, though I notice this release does appear to need the ignore default flag option. Try fixaudio+fixvideo+fixsubtitles(default)+ignoredefault.

If that doesn't work, toss me a link to where I can get these files to test with directly.

**Comment by ztrouy** [comment]
Didn't work sadly, failed to build. 

Here's the link I believe

http://www.moebatch.ga/2016/09/boku-no-hero-academia-english-subtitle.html

**Comment by ztrouy** [comment]
It completely failed to build a file sadly.

Here, I've uploaded what I'm working with at the moment, hopefully you have success in it, or find an issue that is causing it to fail!

https://mega.nz/#!wMUDXBDB!jtPGlKIB_gieuM78LaEi-aewnB5aa0ODO2JeQDqRmhg

Good luck!

**Comment by gnoling** [comment]
I believe I tracked down the original encodes for this, the "hi10" anime group has released...questionable encodes before that I've had other reports for unrelated issues on as well.

The release requires --fixvideo and also --ignoredefaultflag, the problem is ffmpeg was bailing on the ending file and required the -max_muxing_queue_size option to be specified/increased from default. I uploaded a new version of unlinkmkv that updates the ini format and allows customization of the encoding settings, and also added that option to the default encoding settings. Make sure you update both unlinkmkv AND your ini file from the updated example ini.

Secondly, be mindful that this release has a decently-high quality at a low bitrate, while the unlinkmkv defaults are tuned towards higher bitrate files. Theres a good chance you'll want to tweak the encoding settings for the output to not look awful.

**Comment by ztrouy** [comment]
I do have a question, how am I to update UnlinkMKV? I understand how to update the .ini, however the executable is beyond me. The executable within the zip within the master zip shows that it was last updated in August, while the "unlinkmkv" file in the master zip is not an executable (I do apologize if I'm completely forgetting something)

**Comment by gnoling** [comment]
Sorry, you mentioned StrawberryPerl earlier so I thought you were running from source. I updated the windows build in the dist/ with the new version now.

**Comment by ztrouy** [comment]
No worries! I'll check when I get home from work to see if it's all solved, then try and remember how to modify settings to get desirable results

**Comment by ztrouy** [comment]
Everything is working perfectly now! Thank you very much for your time and patience, it's much appreciated!
