### ISSUE TITLE
Empty output file

### ISSUE THREAD

**Issue by piotrp** [gnoling/UnlinkMKV#34]
Generated output mkv file is less than 5 KB, looks like an empty container.

Log: [trace.log](https://github.com/gnoling/UnlinkMKV/files/2545441/trace.log)

mkvtoolnix version:
```sh
root@c46385bdda91:/work# mkvinfo --version
mkvinfo v28.2.0 ('The Awakening') 64-bit
```

Environment: Ubuntu 18.04.1 LTS Docker image, run with video directory mounted as /work. I build it after Windows version didn't work, in hope that maybe on linux it would work.
```sh
#!/bin.bash
apt-get update
apt-get install -y ca-certificates wget gnupg2
wget -q -O - https://mkvtoolnix.download/gpg-pub-moritzbunkus.txt | apt-key add -
echo "deb http://mkvtoolnix.download/ubuntu/ bionic main" > /etc/apt/sources.list.d/mkvtoolnix.list
apt-get update
apt-get install -y mkvtoolnix ffmpeg perl libxml-perl libxml-libxml-perl libfile-which-perl libipc-run3-perl liblog-log4perl-perl libstring-crc32-perl
cd /work
wget https://raw.githubusercontent.com/gnoling/UnlinkMKV/master/unlinkmkv
wget -O unlinkmkv.ini https://raw.githubusercontent.com/gnoling/UnlinkMKV/master/unlinkmkv.ini.dist
sed -ri 's#/opt/ffmpeg/bin/ffmpeg#/usr/bin/ffmpeg#' unlinkmkv.ini
chmod +x unlinkmkv
```

If you need I can send you an email with links to drive with files that fail to merge (165 MB).

**Comment by gnoling** [comment]
Try using **--ignoredefaultflag**, I think that might be what your files need. Failing that, feel free to send me an email with those links and I'll take a closer look.

**Comment by piotrp** [comment]
Thanks, that helped. Lesson learnt: read option list, twice.

**Comment by gnoling** [comment]
Good to hear, closing this
