### ISSUE TITLE
Unlinking files with missing streams

### ISSUE THREAD

**Issue by ReneHollander** [gnoling/UnlinkMKV#36]
Hi,

A subset of episodes (OVAs) from specific are missing the English audio track, while the linked OP and ED still contain it. This  causes a stream mismatch within UnlinkMKV.
I tried to remove the English tracks from the OP and ED to get the OVAs unliked, but it results in the segments being messed up.

Log files: https://gist.github.com/ReneHollander/4003593cc2964b3863917e20b2af373c
MKV files: https://mega.nz/#!MxgC2I5J!wZtCFSn5SCKIvfK0B3X3Z2g-66jw39ebiZMtLJZ_nvI

Is there a known workaround for the issue or an idea on how to fix it?

**Comment by gnoling** [comment]
Those files are...interesting to say the least. I've absolutely had more then one report about Hi10p files in particular.

It appears the opening/ending files both have the english track still as you mentioned, with the main episode instead having two subtitle tracks where the op/ed have just one. Once you pre-prepare the tracks, and _also_ strip all chapters, they can be manually merged (as once you remove the chapters, there's no unlinking to do...).

I hate to say it, but you might be best off stripping off the chapters and just not watching the OP/ED in this file if downloading/watching a different version isn't possible. These would require too much manual fixing to be anything near worth the trouble.

**Comment by ReneHollander** [comment]
Okay, I will leave the OVAs as they are. The normal episodes worked fine, only the OVAs have extra tracks which it does not like.
Don't know if you want to close the issue, or keep it open to maybe pursue something like a filter option (Like remove stream 2 from file X before merging or map stream 2 to stream 3 and stream 3 to stream 2). This should be quite easy to do with ffmpegs `-map` option, if ffmpeg does not screw up the segment ids (which MKVtoolnix did).

Thanks nonetheless!
