### ISSUE TITLE
Unable to start UnlinkMKV on ArchLinux

### ISSUE THREAD

**Issue by Sonico98** [gnoling/UnlinkMKV#41]
I've tried both using the package available on the AUR and cloning the repository and installing dependencies manually. If I run unlinkmkv on the terminal, this is the output:
`UnlinkMKV
Usage: Cwd::abs_path(pathsv=Nullsv) at /usr/bin/unlinkmkv line 101.`

The packages I have installed are:

> core/perl
> extra/ffmpeg
> extra/mkvtoolnix-cli
> extra/mkvtoolnix-gui
> extra/perl-xml-libxml
> extra/perl-ipc-run3
> extra/perl-file-which
> extra/perl-string-crc32
> extra/perl-log-log4perl
> extra/perl-math-bigint

If any more information should be given, please tell me. I'm not really sure what should be posted when reporting something.

**Comment by gnoling** [comment]
I'm unfamiliar with the AUR package so I can't comment on that one.

It looks like there might be an issue with the script resolving relative paths to needed binaries like ffmpeg which is the default behaviour, which I'll work on when I get some time.

In the meantime, do you have an unlinkmkv.ini set up? For the source version the file comes as unlinkmkv.ini.dist and you need to copy it to unlinkmkv.ini the same directory as the script, then customize it -- set absolute paths to the binaries there and that should do the trick. Specifically the error you mentioned appears to be for ffmpeg in particular, but it's likely you'll need to set all five of the paths mentioned there.

**Comment by Sonico98** [comment]
That was it, thank you! Only the path to ffmpeg was wrong, pointing to /opt/ffmpeg/bin/ffmpeg instead of /usr/bin/ffmpeg. Thank you for the quick response and the time you put on UnlinkMKV.
