### ISSUE TITLE
Missing segments on Arch Linux

### ISSUE THREAD

**Issue by lunik1** [gnoling/UnlinkMKV#42]
Hello, I am getting a missing segment error when running this script on Arch Linux. [Here is a full log with -ll TRACE](https://gist.githubusercontent.com/lunik1/46fbc8662b6a34a070cf14f5de9336ad/raw/6b18a3fe87645061a863bbd63ddec6dc0d9b0a08/out.log). The file seems to play fine in mpv.

`LANG` is set to `en_US.UTF-8` so I don't think this is #21.

**Comment by gnoling** [comment]
I'm not going to have time to work on this today/this weekend, but it does look like a bug. It appears it's identifying a segment in "[Sephirotic] Evangelion - The End of Evangelion 25'+26' (Conjoined Ordered Chapter)[C6FDE4FB].mkv" as external, despite it being internal to the file, and that's causing the problem, so it's probably a bug. I won't know for sure until I have some more time with it.

**Comment by gnoling** [comment]
I took a closer look at this and tracked down the original files, this one _might_ be a little beyond the scope of the project but is essentially the same as issue #29 where the script doesn't support complicated timelines where multiple pieces come from multiple files. I'm going to close this in favor of that issue.
