### ISSUE TITLE
File does not contain segmented chapters

### ISSUE THREAD

**Issue by kvloover** [gnoling/UnlinkMKV#43]
Hi, 

I'm getting a 'file does not contain segmented chapters' error when running. Either with the windows bin or the perl script through strawberryperl

The file holds a link to the OP at the very start.

UnlinkMKV
   [ini] [ffmpeg] = [C:\Users\Kevin\Downloads\unlinkmkv/ffmpeg/bin/ffmpeg]
   [ini] [mkvext] = [C:\Users\Kevin\Downloads\unlinkmkv/mkvtoolnix/mkvextract]
   [ini] [mkvinfo] = [C:\Users\Kevin\Downloads\unlinkmkv/mkvtoolnix/mkvinfo]
   [ini] [mkvmerge] = [C:\Users\Kevin\Downloads\unlinkmkv/mkvtoolnix/mkvmerge]
   [ini] [mkvpropedit] = [C:\Users\Kevin\Downloads\unlinkmkv/mkvtoolnix/mkvpropedit]
   [ini] [fixaudio] = [0]
   [ini] [fixvideo] = [0]
   [ini] [fixsubtitles] = [1]
   [ini] [ignoredefaultflag] = [0]
   [ini] [chapters] = [1]
   [ini] [fixvideotemplate] = [-c:v libx264 -b:v {var_minrate}k -minrate {var_minrate}k -maxrate {var_maxrate}k -bufsize 1835k -max_muxing_queue_size 4000]
   [ini] [fixaudiotemplate] = [-map 0 -acodec ac3 -ab 320k]
   [ini] [var_minrate] = [(var_size * 1.1) / var_duration]
   [ini] [var_maxrate] = [var_minrate * 2]
      Options
         chapters: 1
         cleanup: 1
         edition: 1
         ffmpeg: C:\Users\Kevin\Downloads\unlinkmkv\ffmpeg\bin\ffmpeg.EXE
         fixaudio: 0
         fixaudiotemplate: -map 0 -acodec ac3 -ab 320k
         fixsubtitles: 1
         fixvideo: 0
         fixvideotemplate: -c:v libx264 -b:v {var_minrate}k -minrate {var_minrate}k -maxrate {var_maxrate}k -bufsize 1835k -max_muxing_queue_size 4000
         ignoredefaultflag: 0
         mkvext: C:\Users\Kevin\Downloads\unlinkmkv\mkvtoolnix\mkvextract.EXE
         mkvinfo: C:\Users\Kevin\Downloads\unlinkmkv\mkvtoolnix\mkvinfo.EXE
         mkvmerge: C:\Users\Kevin\Downloads\unlinkmkv\mkvtoolnix\mkvmerge.EXE
         mkvpropedit: C:\Users\Kevin\Downloads\unlinkmkv/mkvtoolnix/mkvpropedit
         outdir: C:\Users\Kevin\Downloads\unlinkmkv\UMKV
         tmpdir: C:\Users\Kevin\Downloads\unlinkmkv\UMKV.tmp
         var_maxrate: var_minrate * 2
         var_minrate: (var_size * 1.1) / var_duration
   created tmp C:\Users\Kevin\Downloads\unlinkmkv\UMKV.tmp\8400
   processing C:\Users\Kevin\Downloads\unlinkmkv\s01e01.mkv
      checking if file is segmented
            sys > C:\Users\Kevin\Downloads\unlinkmkv\mkvtoolnix\mkvextract.EXE chapters C:\Users\Kevin\Downloads\unlinkmkv\s01e01.mkv
            sys < ´╗┐<?xml version="1.0"?>
            sys < 
            sys < <Chapters>
            sys <   <EditionEntry>
            sys <     <EditionFlagHidden>0</EditionFlagHidden>
            sys <     <EditionFlagDefault>0</EditionFlagDefault>
            sys <     <EditionUID>1402717579</EditionUID>
            sys <     <ChapterAtom>
            sys <       <ChapterUID>2424613264</ChapterUID>
            sys <       <ChapterTimeStart>00:00:00.000000000</ChapterTimeStart>
            sys <       <ChapterFlagHidden>0</ChapterFlagHidden>
            sys <       <ChapterFlagEnabled>1</ChapterFlagEnabled>
            sys <       <ChapterDisplay>
            sys <         <ChapterString>Part A</ChapterString>
            sys <         <ChapterLanguage>und</ChapterLanguage>
            sys <       </ChapterDisplay>
            sys <     </ChapterAtom>
            sys <     <ChapterAtom>
            sys <       <ChapterUID>1184444839</ChapterUID>
            sys <       <ChapterTimeStart>00:07:13.944000000</ChapterTimeStart>
            sys <       <ChapterFlagHidden>0</ChapterFlagHidden>
            sys <       <ChapterFlagEnabled>1</ChapterFlagEnabled>
            sys <       <ChapterDisplay>
            sys <         <ChapterString>Part B</ChapterString>
            sys <         <ChapterLanguage>und</ChapterLanguage>
            sys <       </ChapterDisplay>
            sys <     </ChapterAtom>
            sys <     <ChapterAtom>
            sys <       <ChapterUID>364199564</ChapterUID>
            sys <       <ChapterTimeStart>00:17:57.944000000</ChapterTimeStart>
            sys <       <ChapterFlagHidden>0</ChapterFlagHidden>
            sys <       <ChapterFlagEnabled>1</ChapterFlagEnabled>
            sys <       <ChapterDisplay>
            sys <         <ChapterString>Lucky Channel</ChapterString>
            sys <         <ChapterLanguage>und</ChapterLanguage>
            sys <       </ChapterDisplay>
            sys <     </ChapterAtom>
            sys <     <ChapterAtom>
            sys <       <ChapterUID>863260575</ChapterUID>
            sys <       <ChapterTimeStart>00:20:21.944000000</ChapterTimeStart>
            sys <       <ChapterFlagHidden>0</ChapterFlagHidden>
            sys <       <ChapterFlagEnabled>1</ChapterFlagEnabled>
            sys <       <ChapterDisplay>
            sys <         <ChapterString>Ending</ChapterString>
            sys <         <ChapterLanguage>und</ChapterLanguage>
            sys <       </ChapterDisplay>
            sys <     </ChapterAtom>
            sys <     <ChapterAtom>
            sys <       <ChapterUID>1430044578</ChapterUID>
            sys <       <ChapterFlagHidden>0</ChapterFlagHidden>
            sys <       <ChapterFlagEnabled>1</ChapterFlagEnabled>
            sys <       <ChapterTimeStart>00:21:51.944000000</ChapterTimeStart>
            sys <       <ChapterDisplay>
            sys <         <ChapterString>Preview</ChapterString>
            sys <         <ChapterLanguage>und</ChapterLanguage>
            sys <       </ChapterDisplay>
            sys <     </ChapterAtom>
            sys <   </EditionEntry>
            sys < </Chapters>
         file does not contain segmented chapters
      removed tmp C:\Users\Kevin\Downloads\unlinkmkv\UMKV.tmp\8400
      created tmp C:\Users\Kevin\Downloads\unlinkmkv\UMKV.tmp\8400
   removed tmp C:\Users\Kevin\Downloads\unlinkmkv\UMKV.tmp\8400
   removed tmp C:\Users\Kevin\Downloads\unlinkmkv\UMKV.tmp
   exiting

**Comment by gnoling** [comment]
This looks likely to be the same issue from #21, can you please try the version just pushed to master? The dist/ has not been updated yet. I'm unsure if this is actually the locale issue, or how the --ui-language option behaves on Windows, so I'd appreciate the feedback. Thanks!

**Comment by kvloover** [comment]
sys > C:\Users\Kevin\Downloads\unlinkmkv\mkvtoolnix\mkvextract.EXE --ui-language en_US chapters C:\Users\Kevin\Downloads\unlinkmkv\s01e01.mkv
            sys < Error: There is no translation available for 'en_US'.
         file does not contain segmented chapters

**Comment by gnoling** [comment]
Alright, I pushed an update that now sets the --ui-language based on the _locale_ ini value; It defaults to **en_US** (linux/not-windows), and for windows it appears to need to be just "**en**". I went ahead and updated the windows dist archive in the repository as well, which also brings in an updated ffmpeg and mkvtoolnix.

If you want to use the repo/script version make sure you set up unlinkmkv.ini and set the locale line to:
```
locale = en
```

The windows dist sets the above already in the archive.

**Comment by IAmEmphy** [comment]
I have the same error message\similar situation, but I have "locale = en" in the .ini file.
Was a bit unsure if I should open a separate issue, but since this is not marked closed, I'll post here first.
This seems to happen with a lot of recent releases (last few years or so), but testing an old release\encode does not exhibit this error.

I've added a trace and a screenshot showing the file does indeed point towards another segment.
(I've also experienced another release way back that did not show Next segment UID, but did load segments, so I'm guessing there are multiple ways to define it? But that's a separate issue if I can remember what release it was...)

[trace.txt](https://github.com/gnoling/UnlinkMKV/files/9490657/trace.txt)
![2022-09-05 16_43_43-MKVToolNix GUI v69 0 0 ('Day And Age') 64-bit](https://user-images.githubusercontent.com/10990465/188474379-b450efa0-c9d4-428c-95e2-f9173ce8b958.png)

**Comment by gnoling** [comment]
> I have the same error message\similar situation, but I have "locale = en" in the .ini file. Was a bit unsure if I should open a separate issue, but since this is not marked closed, I'll post here first. This seems to happen with a lot of recent releases (last few years or so), but testing an old release\encode does not exhibit this error.
> 
> I've added a trace and a screenshot showing the file does indeed point towards another segment. (I've also experienced another release way back that did not show Next segment UID, but did load segments, so I'm guessing there are multiple ways to define it? But that's a separate issue if I can remember what release it was...)
> 
> [trace.txt](https://github.com/gnoling/UnlinkMKV/files/9490657/trace.txt) ![2022-09-05 16_43_43-MKVToolNix GUI v69 0 0 ('Day And Age') 64-bit](https://user-images.githubusercontent.com/10990465/188474379-b450efa0-c9d4-428c-95e2-f9173ce8b958.png)

I think your issue is unrelated, can you please open a new issue instead?
