### ISSUE TITLE
Failed to build Win10

### ISSUE THREAD

**Issue by tucker25** [gnoling/UnlinkMKV#44]
Thanks for the script! it helped me merge some files but there's a few that show "failed to build" i already tried fix audio and fix video and still doesn't work
I'm using strawberry in windows 10
Is there a fix? 

> D:\Download\[Hi10]_Highschool_DxD_[BD_1080p]\[Hi10]_Highschool_DxD_[BD_1080p]>c:\unlinkmkv\unlinkmkv (Hi10)_Highschool_DxD_-_13_(OVA)_(BD_1080p)_(FFF).mkv --ignoredefaultflag
UnlinkMKV
      Options
         chapters: 1
         cleanup: 1
         edition: 1
         ffmpeg: C:\unlinkmkv\ffmpeg\bin\ffmpeg.EXE
         fixaudio: 0
         fixaudiotemplate: -map 0 -acodec ac3 -ab 320k
         fixsubtitles: 1
         fixvideo: 0
         fixvideotemplate: -c:v libx264 -b:v {var_minrate}k -minrate {var_minrate}k -maxrate {var_maxrate}k -bufsize 1835k -max_muxing_queue_size 4000
         ignoredefaultflag: 1
         locale: en
         mkvext: C:\unlinkmkv\mkvtoolnix\mkvextract.EXE
         mkvinfo: C:\unlinkmkv\mkvtoolnix\mkvinfo.EXE
         mkvmerge: C:\unlinkmkv\mkvtoolnix\mkvmerge.EXE
         mkvpropedit: C:\unlinkmkv/mkvtoolnix/mkvpropedit
         outdir: D:\Download\[Hi10]_Highschool_DxD_[BD_1080p]\[Hi10]_Highschool_DxD_[BD_1080p]\UMKV
         tmpdir: D:\Download\[Hi10]_Highschool_DxD_[BD_1080p]\[Hi10]_Highschool_DxD_[BD_1080p]\UMKV.tmp
         var_maxrate: var_minrate * 2
         var_minrate: (var_size * 1.1) / var_duration
   processing D:\Download\[Hi10]_Highschool_DxD_[BD_1080p]\[Hi10]_Highschool_DxD_[BD_1080p]\(Hi10)_Highschool_DxD_-_13_(OVA)_(BD_1080p)_(FFF).mkv
      checking if file is segmented
         file contains segmented chapters
      generating chapter file
         loading chapters
         non-default chapter kept on purpose
         internal
            chapter start   00:00:0.000000001
            chapter end     00:01:22.040000001
            offset  start   00:00:00.000000000
            offset  end     00:01:22.040000001
            chapter enabled 1
         external
            chapter start   00:01:22.040000001
            chapter end     00:02:52.150000002
            offset  start   00:01:30.110000001
            offset  end     00:02:52.150000002
            chapter enabled 1
         internal
            chapter start   00:02:52.191000002
            chapter end     00:10:21.599000002
            offset  start   00:01:30.110000001
            offset  end     00:10:21.599000002
            chapter enabled 1
         internal
            chapter start   00:10:21.640000002
            chapter end     00:10:31.609000002
            offset  start   00:01:30.110000001
            offset  end     00:10:31.609000002
            chapter enabled 1
         internal
            chapter start   00:10:31.650000002
            chapter end     00:21:56.293000002
            offset  start   00:01:30.110000001
            offset  end     00:21:56.293000002
            chapter enabled 1
         external
            chapter start   00:21:56.293000002
            chapter end     00:23:26.403000003
            offset  start   00:03:0.220000002
            offset  end     00:23:26.403000003
            chapter enabled 1
      writing chapter temporary file
      looking for segment parts
         found part D:\Download\[Hi10]_Highschool_DxD_[BD_1080p]\[Hi10]_Highschool_DxD_[BD_1080p]\UMKV.tmp\12356\parts\(Hi10)_Highschool_DxD_-_OP01_(BD_1080p)_(FFF).mkv
         found part D:\Download\[Hi10]_Highschool_DxD_[BD_1080p]\[Hi10]_Highschool_DxD_[BD_1080p]\UMKV.tmp\12356\parts\(Hi10)_Highschool_DxD_-_ED01_(BD_1080p)_(FFF).mkv
         checking that all required segments were found
         all segments found
      flac check
         reading metadata
      extracting attachments
         found FOT Rodin Pro EB.ttf
         found StoneSansStd-Semibold.otf
         found StoneSansStd-SemiboldItalic.otf
         found AurulentSans-Regular.otf
         found boopee_regular.ttf
         found elmer.ttf
         extracting attachments...
         found baars.ttf
         extracting attachments...
         creating 3 splits from D:\Download\[Hi10]_Highschool_DxD_[BD_1080p]\[Hi10]_Highschool_DxD_[BD_1080p]\(Hi10)_Highschool_DxD_-_13_(OVA)_(BD_1080p)_(FFF).mkv
      setting parts
      extracting subs
      making substyles unique
      mashing unique substyles to all parts
      remuxing subtitles
      building file
      fixing subs, again... (maybe an mkvmerge issue?)
      moving built file to final destination
         file failed to build

**Comment by gnoling** [comment]
Wouldn't be the first time I've had reports for the "Hi10" encodes. Could you re-run that and add:

```-ll trace```

To your command line, and then paste or link to the results? Thanks.

**Comment by tucker25** [comment]
Weird :/ the other episodes worked just fine but mostly the ovas in every season it's giving me this error
Sending a txt file

[unlinkmkv.txt](https://github.com/gnoling/UnlinkMKV/files/5022981/unlinkmkv.txt)

**Comment by gnoling** [comment]
Okay, so the problem is OP01 and ED01 each have an additional audio track, where the episode only has one; what you could do is open the OP/ED in mkvmerge gui, remove the second track (or at least, whichever one you wouldn't miss) and remux them without it. Just make sure to move the original two out of the directory before you try again.

If you really wanted to keep them instead I suppose you could duplicate the track in the episode, so that it has two audio tracks, instead of the one.

**Comment by tucker25** [comment]
Thanks for the answer
I tried twice (removing the en one and keeping the jpn and vice versa) and now i get this error 
Did i forgot to tick something inside mkvtoolnix?

> D:\Download\[Hi10]_Highschool_DxD_[BD_1080p]\[Hi10]_Highschool_DxD_[BD_1080p]>c:\unlinkmkv\unlinkmkv (Hi10)_Highschool_DxD_-_13_(OVA)_(BD_1080p)_(FFF).mkv --ignoredefaultflag
UnlinkMKV
      Options
         chapters: 1
         cleanup: 1
         edition: 1
         ffmpeg: C:\unlinkmkv\ffmpeg\bin\ffmpeg.EXE
         fixaudio: 0
         fixaudiotemplate: -map 0 -acodec ac3 -ab 320k
         fixsubtitles: 1
         fixvideo: 0
         fixvideotemplate: -c:v libx264 -b:v {var_minrate}k -minrate {var_minrate}k -maxrate {var_maxrate}k -bufsize 1835k -max_muxing_queue_size 4000
         ignoredefaultflag: 1
         locale: en
         mkvext: C:\unlinkmkv\mkvtoolnix\mkvextract.EXE
         mkvinfo: C:\unlinkmkv\mkvtoolnix\mkvinfo.EXE
         mkvmerge: C:\unlinkmkv\mkvtoolnix\mkvmerge.EXE
         mkvpropedit: C:\unlinkmkv/mkvtoolnix/mkvpropedit
         outdir: D:\Download\[Hi10]_Highschool_DxD_[BD_1080p]\[Hi10]_Highschool_DxD_[BD_1080p]\UMKV
         tmpdir: D:\Download\[Hi10]_Highschool_DxD_[BD_1080p]\[Hi10]_Highschool_DxD_[BD_1080p]\UMKV.tmp
         var_maxrate: var_minrate * 2
         var_minrate: (var_size * 1.1) / var_duration
   processing D:\Download\[Hi10]_Highschool_DxD_[BD_1080p]\[Hi10]_Highschool_DxD_[BD_1080p]\(Hi10)_Highschool_DxD_-_13_(OVA)_(BD_1080p)_(FFF).mkv
      checking if file is segmented
         file contains segmented chapters
      generating chapter file
         loading chapters
         non-default chapter kept on purpose
         internal
            chapter start   00:00:0.000000001
            chapter end     00:01:22.040000001
            offset  start   00:00:00.000000000
            offset  end     00:01:22.040000001
            chapter enabled 1
         external
            chapter start   00:01:22.040000001
            chapter end     00:02:52.150000002
            offset  start   00:01:30.110000001
            offset  end     00:02:52.150000002
            chapter enabled 1
         internal
            chapter start   00:02:52.191000002
            chapter end     00:10:21.599000002
            offset  start   00:01:30.110000001
            offset  end     00:10:21.599000002
            chapter enabled 1
         internal
            chapter start   00:10:21.640000002
            chapter end     00:10:31.609000002
            offset  start   00:01:30.110000001
            offset  end     00:10:31.609000002
            chapter enabled 1
         internal
            chapter start   00:10:31.650000002
            chapter end     00:21:56.293000002
            offset  start   00:01:30.110000001
            offset  end     00:21:56.293000002
            chapter enabled 1
         external
            chapter start   00:21:56.293000002
            chapter end     00:23:26.403000003
            offset  start   00:03:0.220000002
            offset  end     00:23:26.403000003
            chapter enabled 1
      writing chapter temporary file
      looking for segment parts
         checking that all required segments were found
         missing segment: 0xcf 0x11 0x2d 0x22 0x72 0x69 0xba 0x54 0xda 0x4e 0xb3 0x9d 0x51 0x30 0x29 0x43
         missing segment: 0xb2 0x4f 0x61 0xba 0x0b 0x4a 0x6a 0x2a 0x9f 0xcb 0xa3 0x3d 0x46 0xe7 0x45 0xd4
         missing segments

**Comment by gnoling** [comment]
I believe it will typically keep segment IDs unless there is a conflict in the new file, or if you generated a completely new file from pieces or something. Double check that the new files are in the same folder, and make sure when you remuxed them that you just open them in the mkvmerge gui and untick the track you don't want, then save the new files (and that you move only the old ones to a different folder). If that's what you did, you could try changing the UIDs using the header editor in that same gui; open the original file first and just make sure the new file matches.

**Comment by tucker25** [comment]
I managed to fix it by changing the segment ID and i made sure the new files are in the same folder so i don't get the missing segments error anymore but still "failed to build"

[newfile.txt](https://github.com/gnoling/UnlinkMKV/files/5023670/newfile.txt)

**Comment by gnoling** [comment]
Oof, looks like I failed to notice there were two track problems in your first log. You can actually see the error (before as well) near the very end of the log where it notes another mismatch. This time it's complaining that there is two subtitle tracks in the episode, while there is only one in each of the OP/ED files. It would be basically the same deal, you'd either need to remove one from the episode, or you could duplicate (or include an otherwise empty one) one in the NCOP/NCED files.

**Comment by tucker25** [comment]
Ohh that did it! i tried it with all the files giving trouble and it worked
Thank you! sorry i didn't notice haha this is my first time using a script so i don't understand much
I will be closing the thread now
