### ISSUE TITLE
Permission Denied at 'Encoding Parts'

### ISSUE THREAD

**Issue by mhurron** [gnoling/UnlinkMKV#46]
Full Trace Log At https://pastebin.com/Qky5W6WQ

MacOS 10.15.6

Getting a permission denied error encoding parts after UnlinkMKV has made plenty of temporary files

/usr/local/bin/perl /Volumes/External/hdxd/UnlinkMKV/unlinkmkv
UnlinkMKV
      Options
         chapters: 1
         cleanup: 1
         edition: 1
         ffmpeg: /Volumes/External/hdxd/Highschool_DxD/Highschool_DxD
         fixaudio: 1
         fixaudiotemplate: -map 0 -acodec ac3 -ab 320k
         fixsubtitles: 1
         fixvideo: 1
         fixvideotemplate: -c:v libx264 -b:v {var_minrate}k -minrate {var_minrate}k -maxrate {var_maxrate}k -bufsize 1835k -max_muxing_queue_size 4000
         ignoredefaultflag: 1
         locale: en_US
         mkvext: /Applications/MKVToolNix-49.0.0.app/Contents/MacOS/mkvextract
         mkvinfo: /Applications/MKVToolNix-49.0.0.app/Contents/MacOS/mkvinfo
         mkvmerge: /Applications/MKVToolNix-49.0.0.app/Contents/MacOS/mkvmerge
         mkvpropedit: /usr/local/bin/mkvpropedit
         outdir: /Volumes/External/hdxd/Highschool_DxD/Highschool_DxD/UMKV
         tmpdir: /Volumes/External/hdxd/Highschool_DxD/Highschool_DxD/UMKV.tmp
         var_maxrate: var_minrate * 2
         var_minrate: (var_size * 1.1) / var_duration
   processing /Volumes/External/hdxd/Highschool_DxD/Highschool_DxD/(Hi10)_Highschool_DxD_-_01_(BD_1080p)_(FFF).mkv
      checking if file is segmented
         file contains segmented chapters
      generating chapter file
         loading chapters
         non-default chapter kept on purpose
         internal
            chapter start   00:00:0.000000001
            chapter end     00:00:29.529000001
            offset  start   00:00:00.000000000
            offset  end     00:00:29.529000001
            chapter enabled 1
         internal
            chapter start   00:00:29.571000001
            chapter end     00:13:37.775000001
            offset  start   00:00:00.000000000
            offset  end     00:13:37.775000001
            chapter enabled 1
         internal
            chapter start   00:13:37.816000001
            chapter end     00:13:48.285000001
            offset  start   00:00:00.000000000
            offset  end     00:13:48.285000001
            chapter enabled 1
         internal
            chapter start   00:13:48.327000001
            chapter end     00:21:56.773000001
            offset  start   00:00:00.000000000
            offset  end     00:21:56.773000001
            chapter enabled 1
         external
            chapter start   00:21:56.773000001
            chapter end     00:23:26.883000002
            offset  start   00:01:30.110000001
            offset  end     00:23:26.883000002
            chapter enabled 1
         internal
            chapter start   00:23:26.925000002
            chapter end     00:23:42.941000002
            offset  start   00:01:30.110000001
            offset  end     00:23:42.941000002
            chapter enabled 1
      writing chapter temporary file
      looking for segment parts
         found part /Volumes/External/hdxd/Highschool_DxD/Highschool_DxD/UMKV.tmp/59566/parts/(Hi10)_Highschool_DxD_-_OP01_(BD_1080p)_(FFF).mkv
         checking that all required segments were found
         all segments found
      flac check
         reading metadata
      extracting attachments
         found AurulentSans-Regular.otf
         found baars.ttf
         found boopee_regular.ttf
         found brushtype-semibold.ttf
         found DFPMaru-Md-Kami.ttf
         found FOT Rodin Pro EB.ttf
         found StoneSansStd-Semibold.otf
         found StoneSansStd-SemiboldItalic.otf
         extracting attachments...
         creating 2 splits from /Volumes/External/hdxd/Highschool_DxD/Highschool_DxD/(Hi10)_Highschool_DxD_-_01_(BD_1080p)_(FFF).mkv
      setting parts
      extracting subs
      making substyles unique
      mashing unique substyles to all parts
      remuxing subtitles
      encoding parts
         /Volumes/External/hdxd/Highschool_DxD/Highschool_DxD/UMKV.tmp/59566/parts/split-001.mkv
Permission denied at /Volumes/External/hdxd/UnlinkMKV/unlinkmkv line 988.

It does create split-001.mkv, and a split-002.mkv and possibly another file before it exits and deletes everything. It's not really clear what it did that was denied.

Full Trace Log At https://pastebin.com/Qky5W6WQ

**Comment by gnoling** [comment]
Can you review your unlinkmkv.ini file and command line options? Oddly it would appear to think this path is your ffmpeg binary:
```
ffmpeg: /Volumes/External/hdxd/Highschool_DxD/Highschool_DxD
```
You can see it at the beginning when it displays the option values (not the ini values), and at the end when it tries to pass the path as the binary in the trace output.

**Comment by mhurron** [comment]
Ah, ok there was a typo there. Thanks.
