### ISSUE TITLE
Subtitles broken after unlinking

### ISSUE THREAD

**Issue by jakon2048** [gnoling/UnlinkMKV#5]
I posted it in UnlinkMKV-GUI originally, but I thought it'd be wiser to post here instead: https://github.com/hilts-vaughan/UnlinkMKV-GUI/issues/11

I'm trying to unlink THORA's Spice and Wolf season 1 as well as Coalgirl's version. I keep hitting this issue: http://pastebin.com/g2d2ZSGk

The subtitles show up, but after the OP, all the styles are messed up (to be precise, they're unstyled). The OP styles are fine. Perhaps this happens because the OP is the first file played?

---

I've tried 3 releases. Both Thora's and Coalgirl's releases of Spice and Wolf (s1) don't work. They both use ordered chapters and the OP comes right before the show. There's no show then OP then show.

I've tried WhyNot's Steins;Gate. This is more of a traditional ordered chapter thing. There's some show lead in, then an OP, then back to the show. This works. I used the same mkvmerge version and UnlinkMKV-GUI. The only thing that's different in my test are the shows.

I don't think it's a font issue because the subs shows as if there's no styling associated with them. I think the styles are not being copied properly in the edge case... could you confirm?

---

This has also been documented elsewhere: http://thisdoesnotcompute.org/2013/01/14/undoing-ordered-chapters-part-2-fixing-broken-subtitles/

Any advice?

**Comment by gnoling** [comment]
I'm not sure what version of unlinkmkv UnlinkMKV-GUI's is based on, but mine does have several fixes for this very issue.

I've actually been working on making mine cross-platform compatible so that I can distribute a compiled/standalone version. I'm hoping to have it out today but depending on how things go it might take a couple days.

**Comment by gnoling** [comment]
I've discovered the actual issue, it appears to be either a platform-specific issue with mkvtoolnix or a build issue for said platform. Still looking into a decent fix and/or workaround.

**Comment by gnoling** [comment]
Looks like build issue wins the prize. Use the MKVToolnix from https://www.bunkus.org/videotools/mkvtoolnix/windows/releases/8.3.0/ and NOT the one linked to on the official downloads page for windows builds, whoever/whatever builds it at the external site has a mime type issue for truetype collections.

**Comment by jakon2048** [comment]
I'm on windows using 8.3.0 if that helps.

**Comment by gnoling** [comment]
Both builds I'm talking about are 8.3.0, if you went through the official download page and grabbed the latest 8.3.0 mkvtoolnix, that one has broken mime types and appears to be a compile-time issue. Go through the link I posted, which are not the same compiles, and replace your mkvtoolnix with the one from there and see if that fixes it for you.

**Comment by gnoling** [comment]
Try this:

https://raw.githubusercontent.com/gnoling/UnlinkMKV/master/dist/unlinkmkv-win32.7z

Its a portable precompiled for win32 dist of the new update, preconfigured for a bundled ffmpeg and mkvtoolnix. I tested it with the spice and wolf release you  mentioned and it seems to work fine.

**Comment by jakon2048** [comment]
Cool, thanks! I'll give a shot once I have the chance to.

**Comment by jakon2048** [comment]
Works! Thanks for the prompt fix.
