### ISSUE TITLE
Can't change the output directory to current directory on windows

### ISSUE THREAD

**Issue by WeaselKek** [gnoling/UnlinkMKV#51]
In the ini file I've tried:
outdir = $cwd/merged
outdir = $cd/merged
outdir = %cd%/merged
and none of them resolve.

Anyone know how can I get this to work?

**Comment by gnoling** [comment]
The ini doesn't support variable substitution anywhere but the template fields, and for those only special ones.

For cwd, it _should_ simply require you to use a relative path to begin with, so:

```outdir = merged```

Would put it under merged in the current directory. Is that not working properly in windows?

**Comment by WeaselKek** [comment]
Yeah, that did it. Didn't cross my mind that it would work with a relative path.
