### ISSUE TITLE
Invalid option linkage error for "cleanup!" and "edition=i"

### ISSUE THREAD

**Issue by defron** [gnoling/UnlinkMKV#52]
Attempting to run unlinkmkv on Ubuntu 20.04 I get the below error:

```
~/src/UnlinkMKV/unlinkmkv
UnlinkMKV
Invalid option linkage for "cleanup!"
Invalid option linkage for "edition=i"
```
removing lines 97 and 98 allows me to run and output is good, but if I ever needed to use editions option I'd have to make additional script modifications. Seems like some issue with GetOptions but unable to pinpoint

System information:
OS: Ubuntu 20.04
Perl: v5.30.0
CPAN module versions:
Getopt::Long is up to date (2.52)
XML::LibXML is up to date (2.0207).
IPC::Run3 is up to date (0.048).
File::Which is up to date (1.27).
String::CRC32 is up to date (2.100).
Log::Log4perl is up to date (1.54).
Math::BigFloat is up to date (1.999829).

**Comment by gnoling** [comment]
My immediate guess is something with the newer version of perl then it was last tested with, I'll take a look soon.

**Comment by defron** [comment]
Makes sense. I appreciate you looking into it, and let me know if you need any additional information from me.

**Comment by gnoling** [comment]
Looks like, oddly enough, this is an issue between Getopt::Long and Math::BigInt auto-upgrading/blessing the options. Still working on a fix.

**Comment by gnoling** [comment]
The script as of commit 390c361 should fix this problem. Can you please check?

**Comment by defron** [comment]
Removed modifications, checked out that commit and works, re-ran on a file, worked and file output looks the same as before.

Thanks!
