### ISSUE TITLE
unlinkmkv Cannot Detect Chapter Links in Kill la Kill (coldhell)

### ISSUE THREAD

**Issue by xInsertx** [gnoling/UnlinkMKV#6]
Been using this project for a while with almost no problems minus toradora from coalgirls. But this one straight out fails. It runs through the process but outputs nothing. (is way to quick). Doesn't matter what flags i use.

https://bakabt.me/torrent/180974/kill-la-kill-bd-720-ch
http://www.nyaa.se/?page=view&tid=698428

Any help would be appreciated.

**Comment by gnoling** [comment]
Sure.

It looks like you actually need --ignoredefaultflag to process this release correctly, being mindful that the first episode doesn't contain a linked chapter in this release. Testing against episode 2, which does, that flag appears to resolve the issue for me.

Out of curiosity, what issue did you have with toradora? Have a link to the release you used?

**Comment by xInsertx** [comment]
Thanks for the reply. I'll give the that a try once im home. For future reference is there a way to determine if that flag is required in mkvmergegui?

As for toradora It was coalgirls release http://coalgirls.wakku.to/torrents/%5BCoalgirls%5D_Toradora_%281280x720_Blu-ray_FLAC%29.torrent
Problem was every time i processed the files some would randomly cut sections out and others would be perfect.

**Comment by xInsertx** [comment]
I might aswell raise a separate request for this. If subtitle is 'tagged' as japenese / english / spanish / etc its not reapplied at the end. Always says 'undefined'. I can fix this easily using a mkvmerge just wondering if this can be fixed here.

**Comment by gnoling** [comment]
I'll check out Toradora in a bit, it sounds like you might have needed fixaudio/fixvideo, which re-encodes the video pieces to a merge-compatible format.

I created https://github.com/gnoling/UnlinkMKV/issues/7 for the subtitle issue.

As for seeing if that one flag is needed, you can be using the Chapter Editor in mkvmerge-gui, and looking at the default flags (it can also be fixed there). Though most of the time if it runs past too quickly, it's the first thing to try on the next run.

**Comment by xInsertx** [comment]
Originally I Tried both didn't make a difference. It happens when it hits a segment, it just cuts the audio or video or both and skips ahead 5-10seconds. Some would also cut the preview and that would throw the whole thing out of sync.

It's weird. Other than the missing video/audio sections the subs and sound are synced correctly with the video. CRC checks out so I doubt the files are damaged.

EP11 is an example: its ED is delayed and preview is missing.
EP7 is missing the prologue, rest of the file plays fine.

If I check the parts in the temp folder they appear to be correct but something appears to be going wrong during the merge.

Both of these play fine using the original files on devices supporting the linking.
