### ISSUE TITLE
Problems with some files

### ISSUE THREAD

**Issue by Jolar** [gnoling/UnlinkMKV#8]
I tried the script with different flags (--ignore-default-flag, --no-chapters, --fix-video), but the first external chapter (opening at chstart 00:01:6.274000001) that is muxed in doesn't play. The audio is there, but video is garbled. The ending, the last external chapter, plays as it should.

(Also, the output folder is not respected - the files end up in an UMKV subfolder?)

./unlinkmkv --outdir "/home/johan/Desktop/output/" "(Hi10)_Psycho-Pass_-_05_(BD_1080p)_(Commie)_(644819E4).mkv" 
UnlinkMKV
      Options
         chapters: 1
         ffmpeg: /opt/ffmpeg/bin/ffmpeg
         fixaudio: 0
         fixsubtitles: 1
         fixvideo: 0
         ignoredef: 0
         mkvext: /usr/bin/mkvextract
         mkvinfo: /usr/bin/mkvinfo-gui
         mkvmerge: /usr/bin/mkvmerge
         out_dir: /home/johan/Desktop/Psycho-Pass (BD 1080p)/UMKV
         outdir: /home/johan/Desktop/output/
         tmpdir: /home/johan/Desktop/Psycho-Pass (BD 1080p)/UMKV/tmp
   processing /home/johan/Desktop/Psycho-Pass (BD 1080p)/(Hi10)_Psycho-Pass_-_05_(BD_1080p)_(Commie)_(644819E4).mkv
      checking if file is segmented
         /home/johan/Desktop/Psycho-Pass (BD 1080p)/(Hi10)_Psycho-Pass_-_05_(BD_1080p)_(Commie)_(644819E4).mkv contains segmented chapters
      generating chapter file
         loading chapters
         internal
            chstart 00:00:0.000000001
            chend   00:01:6.274000001
            offset  00:00:00.000000000
            offte   00:01:6.274000001
            chen    1
         external
            chstart 00:01:6.274000001
            chend   00:02:36.288000002
            offset  00:01:30.014000001
            offte   00:02:36.288000002
            chen    1
         internal
            chstart 00:02:36.330000002
            chend   00:21:22.955000002
            offset  00:01:30.014000001
            offte   00:21:22.955000002
            chen    1
         external
            chstart 00:21:22.955000002
            chend   00:22:52.294000003
            offset  00:02:59.353000002
            offte   00:22:52.294000003
            chen    1
      writing chapter temporary file
      looking for segment parts
         found part /home/johan/Desktop/Psycho-Pass (BD 1080p)/UMKV/tmp/10317/parts/(Hi10)_Psycho-Pass_-_ED_03_(BD_1080p)_(Commie)_(7F0AF37A).mkv
         found part /home/johan/Desktop/Psycho-Pass (BD 1080p)/UMKV/tmp/10317/parts/(Hi10)_Psycho-Pass_-_OP_01_(BD_1080p)_(Commie)_(37035A11).mkv
      checking that all required segments were found
      extracting attachments
      creating splits
      setting parts
      extracting subs
      making substyles unique
      mashing unique substyles to all parts
      remuxing subtitles
      building file
      fixing subs, again... (maybe an mkvmerge issue?)
      moving built file to final destination

**Comment by gnoling** [comment]
I can't seem to find a release to test that against, would you happen to have a link?

**Comment by Jolar** [comment]
Oh, sorry - I sent it via PM on the kodi forum, it just feels weird to post links in the "open". The 1080p release; episode 05 is the main file, with OP 01 and ED 03 as external chapters for it.

**Comment by gnoling** [comment]
Yeah, the source files just can't be appended as is and require re-encoding. I tested this with -fv/--fixvideo only and that seemed to do the trick. Audio is fine as-is.

Note the --fixvideo and not --fix-video, it would appear I have to update the documentation!
